apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
spec:
  rules:
  - host: users.k8s.local
    http:
      paths:
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.global.backend.name }}
            port:
              number: 9000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.global.frontend.name }}
            port:
              number: 80
