apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.backend.name }}
  labels:
    run: {{ .Values.global.backend.name }}
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: {{ .Values.global.backend.name }}