version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  node-app:
    build: .
    container_name: node-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    restart: always

  frontend:
    build: ./client
    container_name: react_frontend
    ports:
      - "3000:80"  # Mapeia porta 80 interna do nginx para 3000 host
    depends_on:
      - node-app
    restart: always

volumes:
  mongo-data:
