#!/bin/bash

load_image() {
    minikube image load $1
}

build_backend_image() {
    echo "🛠️  Buildando imagem do backend..."
    cd ./app
    docker build . -t yasminvo1/backend-2
    load_image yasminvo1/backend-2
    cd ..
}

build_frontend_image() {
    echo "🛠️  Buildando imagem do frontend..."
    cd ./client
    docker build . -t yasminvo1/frontend
    load_image yasminvo1/frontend
    cd ..
}

init_minikube() {
    echo "🚀 Iniciando o Minikube..."
    minikube start

    echo "✅ Ativando addons..."
    minikube addons enable ingress
    minikube addons enable dashboard
    minikube addons enable metrics-server

    minikube dashboard &
}

# FLAGS
while getopts ":ib" option; do
   case $option in
      i)
        init_minikube
        ;;
      b)
        build_backend_image
        build_frontend_image
        load_image mongo
        
        echo "📦 Aplicando configuração do banco de dados..."
        cd K8s/db
        kubectl apply -f pv.yaml
        kubectl apply -f pvc.yaml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        cd ../..

        echo "📦 Aplicando configuração do backend..."
        cd K8s/backend
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        cd ../..

        echo "📦 Aplicando configuração do frontend..."
        cd K8s/frontend
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        cd ../..

        echo "🌐 Aplicando ingress..."
        cd K8s
        kubectl apply -f ingress.yaml
        cd ..

        ;;

    esac

done

