apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-db
  labels:
    app: users-db
spec:
  selector:
    matchLabels:
      app: users-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: users-db
    spec:
      containers:
      - name: users-db
        image: mongo
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 27017
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        volumeMounts:
          - name: users-persistent-storage
            mountPath: /var/lib/mongo
      volumes:
        - name: users-persistent-storage
          persistentVolumeClaim:
            claimName: users-pv-claim